cicd 5차 테스트
deployment.yaml 내 컨테이너 이미지와 jenkins에서 푸시한 이미지 태그 불일치로 ImagePullBackOff 발생
우선 latest 태그로 일원화

23:44:26  0.9.1-rc1: digest: sha256:7235cd1b1fad9f02996b84626f0707a43c9f51246d616da05d9fcad65c49743d size: 1785
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] withEnv
[Pipeline] {
[Pipeline] sh
23:44:27  + sed -e s|__IMAGE__|juno6800/fhk-ticketing-member-service:0.9.1-rc1|g fhk-ticketing-member-service/infra/k3s/staging/deployment.yaml
23:44:27  + kubectl -n staging apply -f -
23:44:27  deployment.apps/fhk-ticketing-member-service created
23:44:27  + kubectl -n staging apply -f fhk-ticketing-member-service/infra/k3s/staging/service.yaml
23:44:27  service/fhk-ticketing-member-service created
23:44:27  + kubectl -n staging rollout status deployment fhk-ticketing-member-service --timeout=120s
23:44:27  Waiting for deployment "fhk-ticketing-member-service" rollout to finish: 0 of 2 updated replicas are available...
23:46:34  error: timed out waiting for the condition
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
23:46:34  [WS-CLEANUP] Deleting project workspace...
23:46:34  [WS-CLEANUP] Deferred wipeout is used...
23:46:34  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

Events:
  Type     Reason   Age                    From     Message
  Normal   BackOff  3m48s (x416 over 98m)  kubelet  Back-off pulling image "juno6800/fhk-ticketing-member-service:latest"
  Warning  Failed   3m48s (x416 over 98m)  kubelet  Error: ImagePullBackOff