cicd 3차 테스트
05:58:16  + ./gradlew :fhk-ticketing-member-service:clean :fhk-ticketing-member-service:test :fhk-ticketing-member-service:bootJar --no-daemon
05:58:16  Error: Unable to access jarfile /var/lib/jenkins/workspace/fhk-ticket-reservation/gradle/wrapper/gradle-wrapper.jar
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
05:58:16  [WS-CLEANUP] Deleting project workspace...
05:58:16  [WS-CLEANUP] Deferred wipeout is used...
05:58:16  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE